---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: frigate-forward-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: frigate
  extAuth:
    failOpen: false
    recomputeRoute: true
    headersToExtAuth:
      - accept
      - cookie
      - authorization
      - proxy-authorization
      - x-forwarded-proto
      - x-forwarded-for
      - x-real-ip
    http:
      backendRefs:
        - group: ""
          kind: Service
          name: tinyauth
          namespace: auth
          port: 3000
      path: /api/auth/envoy
      headersToBackend:
        - Remote-User
        - Remote-Name
        - Remote-Email
        - Remote-Groups
        - Remote-Sub
