---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11
            env:
              TZ: America/New_York
              LOG_LEVEL: info
              JELLYFIN_PublishedServerUrl: http://jellyfin.reyaan.dev
              JELLYFIN__HTTP_PORT: &http 8096
              JELLYFIN__STREAM_PORT: &stream 7359
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *http
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 400Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *http
          stream:
            port: *stream
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.reyaan.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: miroir
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /config
      media:
        existingClaim: media
        globalMounts:
          - path: /media
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
      tmp:
        type: emptyDir
