---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre-web-automated
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calibre-web-automated-secret
    template:
      data:
        HARDCOVER_TOKEN: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: hardcover
