---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: Pocket ID
      auto_login: "true"
      allow_sign_up: "true"
      use_pkce: "true"
      client_id: 392f9c79-1716-43dd-b9ad-7ac7d9dda674
      scopes: openid email profile groups
      auth_url: https://id.reyaan.dev/authorize
      token_url: https://id.reyaan.dev/api/oidc/token
      api_url: https://id.reyaan.dev/api/oidc/userinfo
      login_attribute_path: preferred_username
      groups_attribute_path: groups
      role_attribute_path: "contains(groups[*], 'admin') && 'Admin' || 'Viewer'"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.reyaan.dev
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc-secret
                      key: client-secret
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
              resources:
                requests:
                  cpu: 10m
                limits:
                  memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  httpRoute:
    spec:
      hostnames:
        - grafana.reyaan.dev
      parentRefs:
        - name: envoy-external
          namespace: network
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: miroir
  disableDefaultSecurityContext: All
