---
apiVersion: miroir.home-operations.com/v1alpha1
kind: MiroirNode
metadata:
  name: gunter
spec:
  pools:
    - name: default
      loopfile:
        baseDir: /var/lib/miroir
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: miroir
provisioner: miroir.home-operations.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  miroir.home-operations.com/replicas: "1"
  csi.storage.k8s.io/fstype: ext4
